### ISSUE TITLE
Aurora Keystrokes needs an outdated coremod to work

### ISSUE THREAD

**Issue by ghost** [LambdAurora/AuroraKeystrokes#1]
You Know what i'm talking about
https://github.com/CottonMC/ClientCommands/releases
Doesn't Work On Servers

**Comment by LambdAurora** [comment]
1. On Fabric coremods don't exactly "exist".
2. Fabric allows certain mods to work on more versions without updating: like ClientCommands which doesn't need to be updated for Minecraft 1.15 and still perfectly work.
3. It's a client-only mod, it cannot be installed on servers.

**Comment by ghost** [comment]
I mean that i cannot join servers with the dependency
