### ISSUE TITLE
/keystrokes does nothing

### ISSUE THREAD

**Issue by itsbumble** [LambdAurora/AuroraKeystrokes#10]
**Describe the bug**
/keystrokes does nothing

**To Reproduce**
1. /keystrokes

**Expected behavior**
gui opens

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [WINDOWS 10]
 - Minecraft [1.16.5]
 - Fabric [latest]
 - Mods 
![image](https://user-images.githubusercontent.com/78655784/110559846-95558d00-810a-11eb-9501-c29b8b6ded64.png)

 - Version [latest]
 - Branch [curseforge]

**Additional context**

**Comment by UltraBlackLinux** [comment]
This mod requires cotton client commands, since it wasn't updated in a while.

**Comment by itsbumble** [comment]
thanks, i thought it was integrated through fabric api
