### ISSUE TITLE
Config Issue

### ISSUE THREAD

**Issue by aknatnwastaken** [LambdAurora/AuroraKeystrokes#3]
Upon attempting to set the y position of the HUD to a negative integer, the game will sometimes crash. Can't provide any more information since the game did not log the crash.

**Comment by LambdAurora** [comment]
Hello,
this is an unfixable issue as it comes from the configuration library used.
The position entries in the configuration are intended to be floating point values and not integers, with `-5` the game crashed but with `-5.0` the game was still working.

Also in the configuration screen (via `/keystrokes`) it wasn't intended to allow negative values for position.
