### ISSUE TITLE
Get game crash

### ISSUE THREAD

**Issue by Avtem** [LambdAurora/AuroraKeystrokes#5]
i downloaded "aurorakeystrokes-1.2.1-fabric1.16". When i try to launch the game, it crashes - see the attached crash report file 
[crash-2020-07-26_10.29.50-client.txt](https://github.com/LambdAurora/AuroraKeystrokes/files/4977277/crash-2020-07-26_10.29.50-client.txt)

**Comment by LambdAurora** [comment]
The Fabric API you have is obselete, you need to [update it](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/3013647) as the mod uses recent additions.

**Comment by Avtem** [comment]
Oh, i see now! Thank you for your reply, i appreciate it!
Maybe it worth to specify minimum required version of Fabric API on CurseForge page?

**Comment by LambdAurora** [comment]
Yes, I really should, the other error I have done is I have not precised the minimum required version in the mod manifest so Fabric loader doesn't warn you soon enough and let it crash :/
